pipeline {
  agent {
    kubernetes {
      yaml'''
apiVersion: v1
kind: Pod
metadata:
  name: graalvm-22-muslib-maven-jenkins-agent-template
  labels:
    app: jenkins-agent
spec:
  containers:
  - name: builder
    image: developerhelperhub/graalvm-22-muslib-maven:latest
    command:
    - cat
    tty: true
    volumeMounts:
    - name: maven-repo
      mountPath: /root/.m2
  - name: docker
    image: docker:latest
    env:
    - name: DOCKER_HOST
      value: "tcp://172.17.0.1:2375"
    command:
    - cat
    tty: true
    volumeMounts:
      - mountPath: /var/run/docker.sock
        name: docker-sock
  volumes:
  - name: maven-repo
    persistentVolumeClaim:
      claimName: jenkins-agent-maven-repo-pvc
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
      '''
    }
  }
  stages {
    stage('Clone Application Git Repo') {
      steps {
        container('builder') {
          git branch: 'main', changelog: false, poll: false, url: 'https://github.com/developerhelperhub/spring-boot-graalvm-jenkins-pipeline.git'
        }
      }
    }  
    stage('Build Native Image and Compress') {
      steps {
        container('builder') {
          sh '''
            cd spring-boot-rest-api-app
            mvn deploy 
            ls
          '''
        }
      }
    }
  }
}